### ISSUE TITLE
Add support for nested client calls

### ISSUE THREAD

**Issue by dzzh** [kristofa/brave#51]
Currently Brave does not allow to create nested spans on the client side.

E.g. after executing this code 
```java
clientTracer.startNewSpan("span1");
clientTracer.setClientSend();
clientTracer.startNewSpan("span2");
clientTracer.setClientSend();

remoteCall(clientTracer);

clientTracer.setClientReceived();
clientTracer.setClientReceived();
```
only span2 will be logged at the client side. Are there any plans to add support for nested client spans? An example of how it can be done is available [here](https://github.com/leigu/brave/commits/master).

If you want, I can add nested client spans support myself and create a pull request.

**Comment by kristofa** [comment]
Sorry for the long delay to come back to this. Brave is about tracking RPC / service requests so if you stick to this as a concept you don't have multiple nested client levels. A request goes from a client to a server.

It would be possible to introduce a Stack of spans on the client side but you basically only have the cs, cr annotations and you would not see the difference between real rpc requests or multiple nested client calls. I prefer to not go that route now. I hope you can get to an agreement with the provider of system B!
