### ISSUE TITLE
Export ZipkinSpanCollector and SpanProcessingThread metrics

### ISSUE THREAD

**Issue by andredasilvapinto** [kristofa/brave#58]
Some examples:

- spanQueue size of threadPool
- number of active threads
- number of log entries per thread
- EVENT: number of rejected span submissions due to full queue
- EVENT: number of successful span submissions to the thread pool
- EVENT: span submission time to the thread pool
- EVENT: number of bytes sent per emission of log entries to the collector/scribe
- EVENT: span batch emission time to the collector/scribe
- EVENT: number of emission errors to the collector/scribe
- EVENT: number of successful emissions to the collector/scribe
- EVENT: number of lost connections to the collector/scribe

I would suggest having them available via JMX for simplicity (event-based metrics could use max of a sliding window or alternatively send the events to opentsdb or graphite each time the event occurs).

**Comment by kristofa** [comment]
Thanks! this definitely is a valuable proposal. Instead of JMX I would be inclined to use the Metrics library that I'm already using in `flume-zipkin-metrics-sink`.  This probably won't be on my priority list for the next months but if you feel like submitting a pull request, more then welcome!

**Comment by andredasilvapinto** [comment]
metrics would be also cool :)

**Comment by kristofa** [comment]
This is added to wanted/requested features in `contributing.md`.
