### ISSUE TITLE
accessing the current Span on the client

### ISSUE THREAD

**Issue by frenchfrywpepper** [kristofa/brave#62]
I want to access the current SpanId from the client, but the ServerAndClientSpanState and the AbstractAnnotationSubmitter.getSpan() methods are not accessible to me.  Is there another way to obtain access to the current span?  Or would it be reasonable to modify AbstractAnnotationSubmitter.getSpan() to be public?  I'm happy to submit a PR if the latter is reasonable.

**Comment by rAun007** [comment]
See if this class will solve your problem or not : https://github.com/kristofa/brave/blob/master/brave-impl/src/main/java/com/github/kristofa/brave/Brave.java

**Comment by kristofa** [comment]
Hi @frenchfrywpepper, Can you give some more details on what you want to achieve?

**Comment by kristofa** [comment]
@frenchfrywpepper do you still need input? If no answer I will close it.
