### ISSUE TITLE
Brave HTTP headers not set when using spring-impl ServletHandlerInterceptor

### ISSUE THREAD

**Issue by ph0bos** [kristofa/brave#63]
I'm currently using 2.4.1 and have several Spring Boot services accessing each other using Apache HTTP client. The Spring use spring-impl/ServletHandlerInterceptor to intercept the calls.

I am seeing individual service traces (e.g. request, response) with a span count of 1, but never spans of greater than one indicating that tracing is not continued across service calls (e.g. serviceA -> serviceB). 

Debugging using curl/Postman the HTTP headers returned from a traced service I never see any Brave HTTP headers on the responses, would it be expected to observe these headers?

Looking at ServletHandlerInterceptor it would appear as though the headers are never set on the exchange. At what point in the chain (using spring-impl) should these headers be set?

**Comment by ph0bos** [comment]
Update: After giving this some more thought I believe this may be related to fact i'm using servlet 3/async controllers (ListenableFuture<?>). I'm currently looking at passing the trace between the threads to resolve.

**Comment by kristofa** [comment]
@ph0bos did you resolve your issue?

**Comment by ph0bos** [comment]
I believe there is missing functionality for propagating the trace metadata between threads (Servlet 3 Async) rather than a bug.
