### ISSUE TITLE
Issue on ZipkinSpanCollector and Zipkin collector communication

### ISSUE THREAD

**Issue by arensteak** [kristofa/brave#69]
Hi,

It's been a month that I discovered Brave and I am currently struggling with Brave and the Zipkin backend components.

My architecture is as follows:
- Client 1 (inside JVM 1)
- Server 1 (inside JVM 2)
- Server 2 (inside JVM 3)

Ok so let's say that I have the following calls that are made (my program entry point is Client 1):
- Client 1 requests Server 1 (first trace)
- Server 1 requests Server 2 (second trace)
- Server 2 requests Server 1 (third trace)

My problem is that the second trace and the third trace are correctly displayed on the zipkin UI but the first trace shows only the SS and SR annotations. I added some logging (with log4j) inside the collect method of the ZipkinSpanCollector class and I can see the CS and CR annotation of my Client 1 in my logs (with the same span-id and trace-id as the server-side).
Plus: the spanQueue.offer(span) line returns true.

Do you have any idea where my problem could come from?

Best regards,

PS: I posted my question as an issue since I didn't find any google-group or IRC channel talking only about brave. I hope it's not a problem.

-- 
Hugo

**Comment by arensteak** [comment]
Hi,

Just so you know I found the problem. I don't use Spring so the ZipkinSpanCollector.close() method was not used and the spans that were put in the spanQueue were never processed by the SpanProcessingThread.

I temporarly fixed that by calling get() on each element of the futures list when Future.isDone method returns true. I don't think it's a good idea but for now that's what I wanted.

Just in case it helps someone.

Thanks for your project btw.

-- 
Hugo

**Comment by kristofa** [comment]
@arensteak Good that you found the issue! And thanks for explaining the problem. It might indeed help others.  All the best!
