### ISSUE TITLE
Setting the service name for a given endpoint

### ISSUE THREAD

**Issue by suryatech** [kristofa/brave#82]
@kristofa 
I've integrated brave into one of my Java services. Due to some weird issue, the service name in the traces is set as "Unknown Service Name"

<img width="906" alt="screen shot 2015-07-07 at 8 57 06 am" src="https://cloud.githubusercontent.com/assets/6257686/8538159/325b92da-2486-11e5-8a8e-cf320dde2afc.png">

Is there a way to set the service name for the current host ?

**Comment by kristofa** [comment]
I think the problem you have it that you did not set the Endpoint using `EndpointSubmitter`.
You have to set the Endpoint once (ip + port + service name) and next it will be set for each annotation you submit like the server send / server received annotations.

This should fix the problem.

**Comment by kristofa** [comment]
@suryatech did my answer fixed your issue?

**Comment by suryatech** [comment]
@kristofa Your suggestion worked. Thanks :-)
