### ISSUE TITLE
Expected value for X-B3-Sampled header

### ISSUE THREAD

**Issue by suryatech** [kristofa/brave#83]
The HTTP header used to determine if a trace should be sampled ("X-B3-Sampled") is either "1" or "0" as per the information provided at https://twitter.github.io/zipkin/Instrumenting.html

However, passing "0" or "1" would mean false because of the current [implementation](https://github.com/kristofa/brave/blob/master/brave-jersey/src/main/java/com/github/kristofa/brave/jersey/ServletTraceFilter.java#L114-L126 
)

**Comment by kristofa** [comment]
Yes, you are right. I'll fix this now while I'm creating new adapters.

**Comment by kristofa** [comment]
Actually, I won't simply switch from 'true' / 'false' to 1 / 0 as this will brake integration with brave 2.x and it would mean people would have to update all their services to brave 3.0 to get usable traces.

What I'll do for now is support both cases on incoming requests but still use true / false for outgoing requests.

**Comment by suryatech** [comment]
That makes sense. I will modify our clients to accept true/false in addition to 0's and 1's.

Also, when do you think Brave v3 would be out?

**Comment by kristofa** [comment]
@suryatech I can't put a fixed date on when I will release brave 3.0.0 but I expect development to be ready in a few (2 - 3) weeks.

**Comment by kristofa** [comment]
Fixed [in this commit](https://github.com/kristofa/brave/commit/b71d7434399c4b77e8ee4dc45715553ca5782711).

**Comment by suryatech** [comment]
@kristofa thanks!
